### ISSUE TITLE
Dispatching action in reducers is considered as anti-pattern

### ISSUE THREAD

**Issue by jasonslyvia** [raisemarketplace/redux-loop#4] opened 2016-01-20 01:15 UTC
http://redux.js.org/docs/api/Store.html#dispatch

Check the `A Note for Flux Users` section.

**Comment by lukewestby** [comment] 2016-01-20 01:25
Hi @jasonslyvia! Thanks for your feedback. This library doesn't actually dispatch actions in the reducer (redux actively prevents you from doing that). It lets you describe actions you want to happen in the future as a direct result of dispatching the current action. There's always going to be a need to have actions run in sequence in order to convey the status of some asynchronous or side-effecting process to your application. This library just attempts to make the expression of that sequence a first class concern of the reducer in the way that synchronous state transitions are out of the box.

I'm going to close this issue for now, *but* if you've found a scenario where this library truly does attempt to dispatch an action within the reducer then we'll want to fix that as quickly as possible and we'll reopen the issue then.

**Comment by lukewestby** [comment] 2016-01-20 01:31
Actually, let's leave this open as I think other folks might feel the same concern and we should keep the conversation going a while.

**Comment by cormacrelf** [comment] 2016-01-20 22:11
So, three premises:

1. Reducers only act on previous state and new actions.
2. Redux-thunk and other middlewares give you access to getState as well as dispatch in your action creators.

Anything you can do in redux-loop can therefore be done with a middleware.

Why not create something like redux-promise that converts actions with a 'loop' key with an array of actions (use with thunks to actually compose) into a stream of dispatched actions? 

I might actually go implement that.

**Comment by cormacrelf** [comment] 2016-01-20 22:49
You can basically treat your middleware like a big, multi-file recursive function with async recursive abilities. Looks like this:

https://cldup.com/mP3I0KNYc7.png

You could treat an action containing a list of actions like your middleware is a right fold from functional programming.

**Comment by lukewestby** [comment] 2016-01-20 23:28
Hey @cormacrelf, thanks for sharing your thoughts! I've organized some responses here:

> 1. Reducers only act on previous state and new actions.

With redux-loop reducers are still only acting on previous state and new actions. The difference is that instead of deciding what happens to your state _now_, your reducer is deciding what happens to your state _next_. I think that's an important distinction, and it stems from my understanding of synchronous state transitions caused by the reducer as one possible effect an action can have out of all possible actions. There's no reason to make a distinction between synchronous and asynchronous effects on your state, and doing so leads to potential implicit state hiding in your action-creators. 

> 2. Redux-thunk and other middlewares give you access to both the new action and getState() as well
> as dispatch in your action creators.

The intention of redux-loop is to remove effects from action-creators entirely. [This comment](https://github.com/rackt/redux/issues/1182#issuecomment-168590101) on an issue about this subject on redux itself goes into great detail about the many issues that can come from running effects via action-creators, especially thunk. As a thought experiment, how would you test a thunk action creator that does async work to check that things are being called in the order you expect?

> Anything you can do in redux-loop can therefore be done with a middleware.

This is certainly true, and in fact you'll probably be able to do things more concisely with middlewares as well. The issue I have with building my application's effects system as a series of specialized middlewares to handle special action types is that it reinforces that unnecessary distinction between synchronous and asynchronous state transitions _to an even greater degree_ by handling special cases like Promise vs. thunk vs. custom API middleware. I would prefer that everything that happens to my application's state be traceable to a single function or series of functions that have been composed together, async or not.

There are, of course, middlewares that don't pose this issue.

Even if you don't like the way we've done it here, I highly recommend moving your effects out of your action creators using [redux-saga](https://github.com/yelouafi/redux-saga). Your ability to test and rely on your app's behavior will increase. If you don't believe me about getting effects out of action-creators, [Dan Abramov might be able to clarify](https://twitter.com/dan_abramov/status/689636000524562433) :smiley:

**Comment by cormacrelf** [comment] 2016-01-21 00:06
Hm, I like that rewinding point in the comment you linked. I always thought it would be good if replaying the synchronous part of a thunk- or promise-style async request wouldn't just stop.

I think I would be sold if I could see how to implement redux-promise-middleware in a redux-loop reducer. Could that easily be done without storing actual promises in the state?

When you return loop(...) with a batch of promises, how serializable is the state? Where are you keeping those promises?

**Comment by cormacrelf** [comment] 2016-01-21 00:24
Oh, actually I see. You can't do that, because the promises already exist, and you wouldn't get replayability. You need to take it a whole step further back, stop creating promises in your action creators and start creating them in your reducers instead.

I must say it feels pretty weird to be doing API calls in a reducer. There is also no way around having promises in the state.

**Comment by cormacrelf** [comment] 2016-01-21 01:18
My only other issue is making this stuff generic. Let's say I have a reducer that makes all my API calls for me. If I want to add some data dependencies, like fetching a parent when getting a child, then where do I put them? I suppose that's doable with an action creator that does dispatch().then, but that's what we're trying to avoid, because it breaks up the chain of effects. I guess it's not as bad to break the chain in its synchronous part, because fetching the parent's data is a separate async cycle and already think of it as a separate testable unit.

**Comment by lukewestby** [comment] 2016-01-21 03:14
This is really good feedback, I'm finding a lot of places in the documentation where we should have addressed the things you're bringing up.

*To address your concerns about where promises are stored, where they exist in the state, and making API calls in the reducer:*

Promises aren't actually stored anywere. The structure of an effect for a promise is just a plain object with a list of args and a function that would return a promise _if_ it were invoked with those args. If you have a branch of your reducer that returns something like this:
```javascript
loop(
  state,
  Effects.promise(api.getStuff, action.id)
)
```
the reducer will return an object that looks roughly like this:
```javascript
{
  model: state,
  effects: {
    factory: api.getStuff,
    args: [action.id]
  }
}
```
which brings me to a point that I really want to emphasize:

Reducers that return `loop`s are still 100% pure. redux-loop doesn't make reducers impure by making API calls in the reducer, it makes them more powerful while still being pure by allowing them to return a description of the API calls or other effects it expects the store to run in addition to updating the state. You can call a reducer with a given action as many times as you want and it will always return the same object by deep-equality comparison. It is only when the store calls the reducer during a dispatch that effects are executed. This is what makes testing so easy, and it won't be difficult to introduce a "pause" feature like the elm-reactor debugger has to enable replaying actions without causing effects to run over again.

In terms of what happens to those effects after you've returned them from the reducer, effects are extracted from the model by the store and by the custom `combineReducers()` so that you have a state tree which lives next to but separate from an effects tree. If you call `store.getState()` with redux-loop installed and walk the returned object you will never encounter effects or promises or anything but the data you want in your state tree. We could easily provide a `store.getEffects()` function as well if folks wanted that feature for instrumentation purposes.

*To address your concerns about sequence dependency:*

This is definitely more of an architecture concern and less of a point of confusion because I did poorly with the README :relaxed:. Using redux-loop is going to impose certain expectations on your reducer hierarchy in that if you have some action responses that depend on other action responses then you'll be best off putting them at the same level. In other words, if you have parent data fetching effects that depend on the completion of a child effect, then those child effects and state might not actually be child effects and state, but instead might be best placed in the parent as well. State and effects should both exist at the highest level at which they are needed, and can be easily passed as props through the view layer. This is carry-over from the Elm architecture and is certainly more of an opinion and design choice than a technical requirement. If that's a deal-breaker for using this library, then to me that's a totally sensible call.

Hopefully I addressed everything so far, let me know if I left anything out! Thanks again for taking time to raise these questions!

**Comment by cormacrelf** [comment] 2016-01-21 03:41
You should add to the documentation a note about store enhancer composition order. I fiddled for a good while before realizing that you absolutely had to place install() after your middleware, i.e.

```js
var finalCreateStore = compose(
    applyMiddleware(thunk, blah, etc),
    install(),
    // devTools
)(createStore);
```

That way your middleware need not know you're using loop, and doesn't need to namespace everything under 'model' (esp. getState() in thunks and redux-simple-router's historyMiddleware). And, when loop does eventually dispatch actions, they go through the middleware anyway.

**Comment by lukewestby** [comment] 2016-01-21 03:44
Yes, we will definitely add this. My note about enhancer order currently in there is very hand-wavy. If you want to contribute some documentation yourself that would be great too!

**Comment by lukewestby** [comment] 2016-01-21 03:58
Updated!

**Comment by lukewestby** [comment] 2016-01-21 04:01
Since this is now more becoming more general feedback (which is greatly appreciated) and less of a discussion about understanding whether dispatch is occurring in the reducer I'm going to close this one. But, always feel free to open additional issues with more comments and concerns. Just wanna keep things organized and discussions focused.

**Closed by lukewestby** 2016-01-21 04:01 UTC
Labels: discussion
